apiVersion: v1
kind: Service
metadata:
  name: api-server-customer-management
  labels:
    app: api-server-customer-management
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
spec:
  selector:
    app: api-server-customer-management
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
# maintainer: automated-checking
