apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
# maintainer: automated-checking
