apiVersion: v1
kind: Service
metadata:
  name: customer-facing-web-server
  labels:
    app: customer-facing-web-server
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
spec:
  selector:
    app: customer-facing-web-server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
# maintainer: automated-checking
