apiVersion: v1
kind: ConfigMap
metadata:
  name: web-server-config
  labels:
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
data:
  KAFKA_BROKERS: "kafka:9092"
# maintainer: automated-checking
